export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_UP_ERROR = "SIGN_UP_ERROR"

export const LOG_IN_REQUEST = "LOG_IN_REQUEST"
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS"
export const LOG_IN_ERROR = "LOG_IN_ERROR"

export const VIEW_POLL_REQUEST = "VIEW_POLL_REQUEST"
export const VIEW_POLL_SUCCESS = "VIEW_POLL_SUCCESS"
export const VIEW_POLL_ERROR = "VIEW_POLL_ERROR"

export const ADD_NEW_POLL_REQUEST = "ADD_NEW_POLL_REQUEST"
export const ADD_NEW_POLL_SUCCESS = "ADD_NEW_POLL_SUCCESS"
export const ADD_NEW_POLL_ERROR = "ADD_NEW_POLL_ERROR"
